### ISSUE TITLE
Whitelist blank after every restart

### ISSUE THREAD

**Issue by BondiBear** [Cookie-AutoDelete/Cookie-AutoDelete#103]
FF55.0.2 / 64

v1.4.3

Setting anything on the whitelist is currently pointless since every FF restart wipes it completely.
Importing from file also doesn't work so its essentially unusable.

**Comment by mrdokenny** [comment]
Are you using a program/extension that wipes `{your profile}\browser-extension-data`. This is where all WebExtensions store their data. 

As it stands, I can't reproduce it so I can't fix it.

**Comment by BondiBear** [comment]
As far as I can tell, not.
Other FF webextensions I have installed all run fine after restarts.
In that folder I find, as an example, the file 'ublock0.sqlite', which is not deleted.

**Comment by BondiBear** [comment]
After a few weeks I've noticed that **cookies for whitelisted sites that start with or contain numbers** (ex. 8xxxx.xx or 4xxxx.xxx, also xxx.4xxxx.xxx) are deleted. 

Other whitelisted sited that start with letters seem to be ok.

Pls fix if possible, as the extension is currently not usable because of this

**Comment by laktak** [comment]
I have the same issue if I leave the settings (`moz-extension://bfa765c8-f4e6-4a99-8156-58af1cc59a3a/settings/settings.html`) open in a tab and the tab is restored on startup. I guess the settings page is shown before everything is loaded completely.

If I close the tab and then click on preferences again the whitelist will be back.

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
