### ISSUE TITLE
[UX] Active mode??

### ISSUE THREAD

**Issue by rugk** [Cookie-AutoDelete/Cookie-AutoDelete#104]
### Describe the Bug/Feature

In the popup there is a checkbox:
* [ ] active mode

Now, I, as a user, still don't know what happens when I check that box? What is an active mode? What does it change? Does it mean I currently use a "passive mode"? And what are the differences between the modes.

Now looking into the settings I see the sentence (roughly translated):
> When active mode is on, the cleanup is doen when closing a tab.

Now, to be honest, this does not explain a thing for me. Is not that the whole purpose of the add-on? Or does it otherwise only cleanup on shutdown? This should be clarified and you can maybe change the option text to "Cleanup while browsing" or similar if that is the correct behavior.

Please note: You do not need to answer my questions here, I'd rather like to have an implementation/change in the add-on to clarify these questions, as these affect all (new) users. 

### Your settings 

- Cookie AutoDelete version: 1.4.0

**Comment by Atavic** [comment]
Active mode enables the webextension that deletes cookies as soon as the tab closes.
Unchecking it makes the webext inactive, and cookies will stay after closing tabs.

>Or does it otherwise only cleanup on shutdown?

Yes. The checkbox helps when a site has issues and the user has no clues about what to whitelist.

**Comment by Atavic** [comment]
Active mode enables the webextension that deletes cookies as soon as the tab closes.
Unchecking it makes the webext inactive, and cookies will stay after closing tabs.

>Or does it otherwise only cleanup on shutdown?

Yes. It works like Self-Destructing Cookies addon.

The checkbox helps when a site has issues and the user has no clues about what to whitelist.

**Comment by rugk** [comment]
So basically the checkbox just disables the whole add-on? So maybe name it "temporarily disable"?

**Comment by Atavic** [comment]
Seems a better term.

**Comment by rugk** [comment]
…and deactivate it by default (i.e. the add-on should, of course, be activated by default).

**Comment by mrdokenny** [comment]
>temporarily disable

You can use the extension in manual mode as well. You basically turn off Active Mode and use the cleanup buttons manually.

>activated by default

No it shouldn't cause people will probably get annoyed when cleanup gets done without their intervention.

This is a random review from SDC:

>BE CAREFUL
On first run, the Program destroyed all my cookies WITHOUT WARNING and tells me how I can recover it afterwards.
Really? Ridiculous!

**Comment by mrdokenny** [comment]
This is where the "Active Mode" term was inspired from:

https://addons.mozilla.org/firefox/addon/cookies-exterminator/

**Comment by rugk** [comment]
Okay, interesting, but that does not make the confusing term better, because the opposite of "active mode" would be "passive mode" (which would be used when the checkbox is not selected).

**Comment by ariddell** [comment]
I just installed the extension and this is my first concern. If the help could, in addition to the current text, explain what happens when "Active mode" is *not* checked, that would solve this issue for me.

Thank you for the extension. I've left a review on addons.

**Comment by mrdokenny** [comment]
![98898](https://user-images.githubusercontent.com/17077613/29754751-b7695b24-8b40-11e7-91d0-b392884dd652.png)

This is the closest setting in SDC to Active Mode.

**Comment by mrdokenny** [comment]
The "Temporarily" in SDC doesn't make sense in C-AD since Active Mode can be permanently On or Off.

**Comment by mrdokenny** [comment]
It seems like more people are having problems with the term "Active Mode". So I will be taking suggestions for what it should be renamed to. 

Either way, this design decision should be taken carefully since a wording change isn't as simple now because it has to be changed for ALL the locales as well and that takes time depending on the translators.

https://github.com/mrdokenny/Cookie-AutoDelete/tree/master/extension/_locales

**Comment by Merseybuoy** [comment]
I'd suggest the term should be simply "Automatic Cleaning". Then its clearly tick for on and no tick for off.

**Comment by negativeions** [comment]
I mean, really, you download an add-on that knowingly deletes cookies. Presumably you read the description of the add-on to know what it does. Then it does it's job. ARGH! Why did it do it's job!? So active mode is basically the result of a few morons who installed SDC who don't know how to read? I think it should be on by default once installed. Have the temp suspend mode like in SDC. But just post a warning in big letters or something on the add-on page about what will happen once installed and even on the preferences page I guess.

**Comment by neroux** [comment]
I second @rugk concerns. From a UX perspective the term is simply misleading. Up until now I had some assumptions what that could be referring to but I wasnt really sure either.

I'd scrap that toggle altogether. The very idea of the extension is remove cookies automatically and someone installing it shouldnt be surprised if that happens.

If that toggle has to be there by all mean, I'd suggest to "hide" it under some advanced setting, rename it to "Disable automatic cookie removal", and disable that flag by default.

**Comment by Merseybuoy** [comment]
With respect, neroux, your suggestion is confusing in itself.  Does one tick (check) the box to activate or deactivate "Disable automatic cookie removal"?

**Comment by neroux** [comment]
Why would you find it confusing?
- [ ] Disable automatic cookie removal

By default it is unchecked. When ticked it will disable automatic cookie removal

**Comment by neroux** [comment]
Alternatively, considering the extension should also cover local storage at some point, the phrasing could be
- [ ] Disable automatic cleanup

**Comment by Merseybuoy** [comment]
OK, fair enough. I think my point was that you are changing the box to the opposite of it's current function.

**Comment by mrdokenny** [comment]
@neroux 
>The very idea of the extension is remove cookies automatically and someone installing it shouldnt be surprised if that happens

I rather not risk it since there's no recovery once it's gone. Either way, like I said before, I never really liked SDK's way of deleting ALL cookies on install and asking you to restore them later, especially since on install you haven't created your whitelist yet.

@Merseybuoy 
>I'd suggest the term should be simply "Automatic Cleaning".

I like this phrasing so far.

**Comment by neroux** [comment]
> I rather not risk it since there's no recovery once it's gone. Either way, like I said before, I never really liked SDK's way of deleting ALL cookies on install and asking you to restore them later, especially since on install you haven't created your whitelist yet.

I understand your point but would argue that this is what people should expect when they install an extension with that purpose. Also, I understand you clean the cookies only when a tab is closed, so it should not have an immediate effect anyhow.
