### ISSUE TITLE
[UI] Use colors in radio selection, too

### ISSUE THREAD

**Issue by rugk** [Cookie-AutoDelete/Cookie-AutoDelete#107]
What you are IMHO still missing from [Self-Destructing Cookies](https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies/) is the clear color scheme. The color scheme there was:
* **green:** never deleted
* **yellow:** delete after ending browser session
* **red:** always delete after closing tab

You have these options too, in form of radio buttons. However, there is so much text, so that is not nice. 
It would be nice if you could adapt this simple traffic light system.
I see you already adopted it in the icon more or less (green in blue there), but also in the options pane it should be reflected.

**Comment by rugk** [comment]
Changed title to distinguish this issue from https://github.com/mrdokenny/Cookie-AutoDelete/issues/66.

**Comment by mrdokenny** [comment]
Considering that I'm switching to a system where a user can add subdomains or just the domain itself makes this request unnecessary.
