### ISSUE TITLE
Ability to add main domain to whitelist while visiting subdomain

### ISSUE THREAD

**Issue by szpak** [Cookie-AutoDelete/Cookie-AutoDelete#113]
### Describe the Feature

Visiting (for instance) `xxx.slack.com` it is possible to add `xxx.slack.com` to the while/greylist. However, Slack adds generic cookies in `slack.com` which are deleted (and you need to login again). It would be good to be able to add also (on demand) the main level domain (here `slack.com`) from an existing menu while visiting a subdomain.

**Comment by ToddDTaft** [comment]
If you are using standard regular expression syntax, as described in #119, the examples given could be problematic.  "*example.com" matches "host.example.com", but it also matches "badexample.com".  Perhaps you should use a syntax like ".example.com" to mean "example.com" and "*.example.com" (but not "badexample.com")? This syntax seems easier than what the real regular expression would be to do this correctly, and it's probably a very common case that you would want entries from the domain itself as well as its subdomains to be treated the same.

**Comment by somini** [comment]
`\bexample.com` will match example.com and sub.example.com but not badexample.com.

**Comment by somini** [comment]
Without subdomains use a "^" on the start. 

Sorry about the bad formatting, I'm on mobile.

**Comment by mrdokenny** [comment]
>the examples given could be problematic. "*example.com" matches "host.example.com", but it also matches "badexample.com"

You do make a valid point

>Perhaps you should use a syntax like ".example.com" to mean "example.com" and "*.example.com"

I don't think many people are used to using the dot. I seem more examples trying to use the wildcard. 

What I think I might do is follow these examples:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns#Examples

**Comment by szpak** [comment]
Btw @mrdokenny, `^(([a-z0-9]*\.)*example\.com)$` will not match domains with `-` inside.

**Comment by somini** [comment]
Yeah, a-z0-9 seems wrong. Maybe `^|\.`

**Comment by mrdokenny** [comment]
`^([\w\d|-]*\.)*example\.com$`

`example.com` -> match
`badexample.com` -> no match
`a.example.com` -> match
`a.b.example.com` -> match
`a-c.b.example.com` -> match

Any other weird domains I should be worried about?

**Comment by somini** [comment]
Have you tested `(^|\.)example\.com$`? This matches all subdomains without catch-all `.`.
```pyhton
>>> l=['example.com','sub.example.com', 'badexample.com', 'bad.example.com.others.org', 'sub.several.example.com','sub-with-strage_chars.example.another.sub.example.com']
>>> pprint([(d, re.search('(^|\.)example\.com$', d) is not None) for d in l])
[('example.com', True),
 ('sub.example.com', True),
 ('badexample.com', False),
 ('bad.example.com.others.org', False),
 ('sub.several.example.com', True),
 ('sub-with-strage_chars.example.another.sub.example.com', True)]
```

**Comment by mrdokenny** [comment]
@somini I just added that and I'll be testing it for the next couple of days

**Comment by mrdokenny** [comment]
Just some updates on what you can do under this system:

`google.com` -> cookies from just google.com
`*.google.com` -> cookies from google.com and subdomains
`*.google.*` -> cookies from google.com, subdomains, and TLDs (sites like `google.ca`)

**Comment by somini** [comment]
Does `*.google.*` match `bad.google.com.evil.domain.tld`?

**Comment by mrdokenny** [comment]
It does but I don't expect people to use the wildcard to do stuff like `git*b.com` to match `github.com` and `gitlab.com`. It's basically another option that people can use if they want.

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
