### ISSUE TITLE
[Bug] Can’t Changes Settings

### ISSUE THREAD

**Issue by zero77** [Cookie-AutoDelete/Cookie-AutoDelete#117]
**### Describe the Bug/Feature**
After installing the add-on I was unable to change any settings or add any domains to the white or grey list, It is working ok in Firefox nightly but not beta.

**### console output:**
TypeError: browser.extension.getBackgroundPage(...) is null[Learn More]  settingsLocalization.js:1:12
TypeError: browser.extension.getBackgroundPage(...) is null[Learn More]  settings.js:6:21

When I try to load either settingsLocalization.js or settings.js separately in a different tab I get a file not found error.

- OS/version: Windows 8.1
- Browser/version: Newest Firefox Beta
- Cookie AutoDelete version: 1.4.3

**Comment by mrdokenny** [comment]
Probably needs a browser restart or something.

**Comment by zero77** [comment]
I have tried that, it seems like a specific problem with the Firefox beta version as its ok in nightly.

Also it looks completely different it’s all in one page not separate pages like Welcome, Cookie Settings, Cookie WhiteList and About.

**Comment by mrdokenny** [comment]
Interesting that means somehow Javascript is being disabled on the options page. So it's probably an extension conflict.

**Comment by zero77** [comment]
Yes, I was wondering the same thing so, I disabled all other add-ons then tried it but, it makes no difference.

**Comment by dgadelha** [comment]
I'm facing this issue too.

Maybe you could check this: https://stackoverflow.com/questions/7971566/why-does-chrome-extension-getbackgroundpage-return-null

**Comment by mrdokenny** [comment]
I wonder if it's a browser issue?

**Comment by pwn0r** [comment]
confirmed on Developer's version (56b6) -- if multiprocess is disabled (which is normally the case for me) then your extension effectively does not work.

**Comment by zero77** [comment]
Yes, that makes sense because it is working ok in Firefox nightly and multiprocess is enabled by default.

**Comment by dgadelha** [comment]
@pwn0r yes, I'm using Developer Edition (Aurora) too, and it worked only after enabling multiprocess. Although I miss the SDC UI a lot

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
