### ISSUE TITLE
Enable Active Mode: Change the default value from 1 minute to 0.25 minute (15 seconds)

### ISSUE THREAD

**Issue by davidhedlund** [Cookie-AutoDelete/Cookie-AutoDelete#128]
"Enable Active Mode" is set in minutes. Self-Destructing Cookies deletes cookies after 15 seconds.

Can you please:
* Change minutes to seconds.
* Change the countdown from 1 minute to 15 seconds (0.25 minute).

**Comment by davidhedlund** [comment]
15 seconds is much better because then you don't have to sit 1 minute in front of the computer to verify that the cookies are deleted, which is particularly useful if you have to leave as soon as you close the tabs.

**Comment by davidhedlund** [comment]
I asked the author of SDC to recommend your add-on on his AMO page by the way. Good work!

**Comment by mrdokenny** [comment]
See https://github.com/mrdokenny/Cookie-AutoDelete/issues/73#issuecomment-311493047

**Comment by davidhedlund** [comment]
Can you set it to 0.25 minutes in Firefox?

**Comment by doodhout** [comment]
@davidhedlund You apparently can set it to whatever floating point value you want, so yes, of course!

**Comment by davidhedlund** [comment]
@doodhout It was a request from me to @mrdokenny.

Can you please change the default value to 0.25 minutes in Firefox?

**Comment by davidhedlund** [comment]
@doodhout Please read the topic.

**Comment by orbitTVO** [comment]
Maybe try being more clear.

What you actually request from @mrdokenny is for him to set the default value of the timeout from 1 minute to 0.25 minutes.

Nowhere in this thread did you specify you requesting him to change the DEFAULT value. That confused both him and me.

**Comment by doodhout** [comment]
Maybe try being more clear.

What you actually request from @mrdokenny is for him to set the default value of the timeout from 1 minute to 0.25 minutes.

Nowhere in this thread did you specify you requesting him to change the DEFAULT value. That confused both him and me.

**Comment by davidhedlund** [comment]
@doodhout Yes, you are right about that. I changed the topic again.

**Comment by mrdokenny** [comment]
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/FAQ:-Common-Questions-and-Issues#why-does-the-delay-before-cleaning-default-to-1-minute

Basically trying to make it consistent and make it work with as many browsers as possible (Vivaldi users use this extension as well). Maybe in the future when Chromium browsers don't have this limitation, then I can lower it for all.
