### ISSUE TITLE
Cookies for whitelisted sites that start with or contain numbers are deleted

### ISSUE THREAD

**Issue by BondiBear** [Cookie-AutoDelete/Cookie-AutoDelete#130]
FF55.0.3 / 64

v1.4.3

I've noticed that **cookies for whitelisted sites that start with or contain numbers** (ex. 8xxxx.xx or 4xxxx.xxx, also xxx.4xxxx.xxx) are deleted.

Other whitelisted sited that start with letters seem to be ok.

Pls fix if possible, as the extension is currently not usable because of this

**Comment by mrdokenny** [comment]
Do you have an example site so I don't have to artificially create those cookies?

**Comment by BondiBear** [comment]
yes, try this

[https://boards.4chan.org/g/](url)

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
