### ISSUE TITLE
[Bug]  Can't Delete Cookies - Help

### ISSUE THREAD

**Issue by sileeb** [Cookie-AutoDelete/Cookie-AutoDelete#1304]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

I have firefox, latest version, 64 bit on win 10. I thought I deleted cookies for Spectrum TV through firefox and CAD. But when I restart firefox and go to Spectrum TV, I'm signed in automatically. On the CAD icon popup there are no cookies stored. Same thing in firefox's settings. I even deleted cookies.sqlite from my profile. Yet I find myself signed in automatically every time I boot up firefox. How do I fix this??

### To Reproduce

I just visit spectrum tv

### Expected Behavior

I expect not being able to sing in automatically into spectrum tv on firefox

### Screenshots

![11](https://user-images.githubusercontent.com/73712645/150629426-096b71c2-487e-45e1-ae0d-93ece53d7639.png)

_No response_

### System Info - Operating System (OS)

win 10

### System Info - Browser Info

firefox 96.0.2

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
If it is not a cookie then they may be using other storage like localstorage, indexeddb, etc.

**Comment by sileeb** [comment]
Hi kenneth.. I got it working. Excuse the inconvenience. Thank you!
