### ISSUE TITLE
The notification popup don't close (occasionally)

### ISSUE THREAD

**Issue by davidhedlund** [Cookie-AutoDelete/Cookie-AutoDelete#132]
Sometimes the notification message are persistent, then you have to close them manually which is very annoying.

![screenshot from 2017-09-02 04 59 07](https://user-images.githubusercontent.com/6416073/29992442-79d6e8f8-8f9b-11e7-9981-7d2772c675f1.png)

Using Cookie Autodelete 1.4.3

**Comment by mrdokenny** [comment]
They are 10 seconds long and cannot be changed at this time.

**Comment by davidhedlund** [comment]
@mrdokenny No, sometimes they **never** close. I waited at **least 5 minutes** before I gave up and closed it manually.

**Comment by mrdokenny** [comment]
That doesn't sound right. Since I never had this happen, I'm going to assume either something is wrong with your Firefox profile or there's an extension conflict.

**Comment by BoffinbraiN** [comment]
You can easily adjust the length of time a notification lasts if you set a manual timeout to close it.
Please see the below code which I use in some Greasemonkey scripts of mine. I would (perhaps naively) assume the same features are available when using WebExtensions.

    var n = new Notification("Notification title", {body: "Hello, world!"});
    window.setTimeout(function() {n.close();}, 1000);

**Comment by davidhedlund** [comment]
@BoffinbraiN That is very kind of you, but I just wanted to report the bug so I can use a working version.

**Comment by BoffinbraiN** [comment]
@davidhedlund Actually, that comment was directed at @mrdokenny so he can fix the issue. I wouldn't expect you to have to write this yourself!

**Comment by davidhedlund** [comment]
@BoffinbraiN I see. Thank you for clarifying.

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
