### ISSUE TITLE
No cookies will be deleted

### ISSUE THREAD

**Issue by Symbai** [Cookie-AutoDelete/Cookie-AutoDelete#135]
### Describe the Bug/Feature

I visit youtube, enable dark theme (easiest way to see if cookies get deleted).
Close all youtube tabs. Wait some seconds, open new youtube tab and dark theme is still active.

Also you can open the cookies in FF to see youtube cookies will not be deleted at all.
I'm new to this addon so perhaps I have missed something but my expectations would be that cookies for the site will be deleted when i close the tab and in this case, it does not.

There is no whitelist for YT or any other google service.

### Steps for anyone to reproduce the bug

1. Visit YT
2. Enable dark theme
3. Close tab
4. Wait
5. Visit YT and see dark theme is still active. Alternatively open cookie viewer in FF and search for youtube.com

### Your settings 

[X] Delete after closing tab
[ ] Active mode (unchecked)

- OS/version:  Windows 8.1 64bit
- Browser/version:  FF 55.0.3 (E10 mode active)
- Cookie AutoDelete version:  1.4.3

**Comment by mrdokenny** [comment]
Enable 'Active Mode'

**Comment by Symbai** [comment]
So without active mode this addon does nothing? I thought active mode cleans periodically even if I dont close any tabs?

**Comment by mrdokenny** [comment]
There's a delay before clean that you can edit in your settings. If you want instant cleanup then you can set it to 0.

**Comment by Symbai** [comment]
But wouldn't that clear ALL cookies? Lets say i have three tabs opened:

- Online banking
- Youtube
- A white listed site

With your settings, if I close the YT tab, wouldn't it also delete the cookie of my online banking tab even if its still opened?

By "Clear on tab close" I would expect this addon just deletes the cookie of this specific site since, its no longer used. This would have been a perfect situation since I allow a cookie as long as I visit the site but when I close the site, im done and the cookie is no longer needed.

**Comment by mrdokenny** [comment]
>With your settings, if I close the YT tab, wouldn't it also delete the cookie of my online banking tab even if its still opened?

Nope

> By "Clear on tab close" I would expect this addon just deletes the cookie of this specific site since, its no longer used. This would have been a perfect situation since I allow a cookie as long as I visit the site but when I close the site, im done and the cookie is no longer needed.

Yes.

Please read usage on the extension description:

Usage
This extension does not clean cookies automatically until you click "Active Mode". This gives you the chance to add sites to the WhiteList.

1. Add the sites you want to keep cookies in the WhiteList (permanently) or GreyList (until Browser restart)
2. Enable "Active Mode" in the popup or settings
3. Watch those unused cookies disappear :)

The delay is used IN CASE you accidentally closed a tab and want to reopen it to prevent cleanup of those cookies.
