### ISSUE TITLE
Cookies deleting only after closing 2 tabs if timer set to 0

### ISSUE THREAD

**Issue by Paulvin** [Cookie-AutoDelete/Cookie-AutoDelete#137]
When you set your autodelete timer to 0 or .001 you need to at least close 2 tabs if you want to delete your cookie on the current page. It works if I set the timer to .01 though. I have tried this on a new firefox install and a new profile and it still persists.
 
[https://imgur.com/a/qQrNS](url)

as you can see in the screenshots randomshit.com and drugabuse.gov only got deleted when i close 2 tabs. reddit.com's cookies will only get deleted if I close the temporary email website.

- OS/version: Windows 7
- Browser/version: Firefox 55.0.3
- Cookie AutoDelete version: 1.4.3

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
