### ISSUE TITLE
[Bug]  Accumulating More Unneeded Cookies than Before

### ISSUE THREAD

**Issue by sileeb** [Cookie-AutoDelete/Cookie-AutoDelete#1381]
### Acknowledgements

- [X] I acknowledge that I have read the above items

### Describe the bug

On firefox for desktop, I cleared all cookies in firefox's settings. But immediately upon checking in firefox's settings, I see 1.1GB accumulated cookies after I logged in to only 2 sites and after I restarted firefox. Now, total cookies number 5.3MB. Before I cleared all cookies, my accumulated cookies was no more than 300 - 400Kb and logging into 10 sites in total.

### To Reproduce

n/a

### Expected Behavior

Accumulated cookies shouldn't exceed 300 - 400kb.

### System Info - Operating System (OS)

win 10

### System Info - Browser Info

firefox 100.0

### System Info - CookieAutoDelete Version

3.6.0

**Comment by kennethtran93** [comment]
Closing as the Issue above already has a fix.

Also, keep in mind that the storage size shown is not all cookies, but other site data including cache, indexeddb, localstorage, service workers, etc.  Part of the reason why it accumulated more than before is due to the above mentioned issue.
