### ISSUE TITLE
Incognito check

### ISSUE THREAD

**Issue by neroux** [Cookie-AutoDelete/Cookie-AutoDelete#139]
Is there a particular reason why the popup is disabled for incognito windows?

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/master/src/background.js#L294

**Comment by mrdokenny** [comment]
WebExtensions don't have access to private browsing cookies. Also, from what I recall, WebExtensions can't also access what the current URL of the tab in private browsing.

**Comment by neroux** [comment]
Are you sure, have you tried it? As far as I can tell it works just fine, the notification is shown and cookies seem to be deleted. At least with Chrome 62

**Comment by mrdokenny** [comment]
Are those cookies from private browsing or just regular cookies?

**Comment by neroux** [comment]
Private browsing. Legacy Firefox extensions could not access cookies from private browsing, I would need to check whether Firefox does the same for web extensions but in Chrome it does work.

**Comment by neroux** [comment]
@mrdokenny Can this be fixed for Chrome?

**Comment by neroux** [comment]
@mrdokenny Any updates on this?

**Comment by ke-d** [comment]
@neroux According to [this](http://piro.sakura.ne.jp/latest/blosxom/mozilla/extension/treestyletab/2017-10-03_migration-we-en.htm).

> (By the way, there is an API browser.runtime.getBackgroundPage() to access the namespace of the background script from sidebar scripts, but TST doesn't use it and using browser.runtime.sendMessage() for all massaging between background and sidebar scripts, because browser.runtime.getBackgroundPage() doesn't work on private-browsing windows.)

`browser.runtime.getBackgroundPage()` was used in 1.X.X and so the popup could not communicate with the background page. In 2.X.X, message passing was used so I'll lift the restrictions and see what works.

**Comment by neroux** [comment]
My understanding is that restriction only applied to Firefox. My question was regarding Chrome though.
