### ISSUE TITLE
UX Improvements for the Android Popup

### ISSUE THREAD

**Issue by pwd-github** [Cookie-AutoDelete/Cookie-AutoDelete#140]
### Describe the Bug/Feature

The popup contents are way too small.

### Screenshot in which the bug can be seen

![screenshot_2017-09-08-16-21-59](https://user-images.githubusercontent.com/203217/30218885-3d1d9472-94b2-11e7-8394-f402dda33485.png)

### Steps for anyone to reproduce the bug

1. Open Firefox for Android
2. Open the menu
3. Tap Cookie AutoDelete
4. Squint

### Your settings 

- OS/version: Android 7.0
- Browser/version: Firefox Nightly
- Cookie AutoDelete version: 1.4.3

**Comment by mrdokenny** [comment]
I know about this, but have you tried any other WebExtension to see they have the same issue?

A workaround would be to zoom in.

Otherwise, this problem can probably be fixed by messing around with the CSS which takes a long time for me.

**Comment by pwd-github** [comment]
Oh, I've been zooming in. Just thought I'd try and stick this on your radar. The WebExtension that's done the best job of this thus far is Decentraleyes. If I can get it to open up as a mobile page on my laptop, I'll mess with the CSS and submit a pull request.

**Comment by mrdokenny** [comment]
Well, I'm not using the 1.X.X branch anymore since 2.X.X has some major improvements. One of which is large portions of the code is rewritten in React/Redux (which means there's some migration code to switch to Redux storage format). It's in the state of alpha but getting closer to beta. I'll have more information when I'm ready to release the beta of 2.X.X

**Comment by pwd-github** [comment]
Well in that case, I'll just leave this here, it's a WIP

In popup.css FIND:
`span {
  font-size: 1.9rem;
  
}

span.userAction {
  font-size: 16px;
  font-weight: 300;
  text-align: center;
}

label:hover {
  background-color: #d3d3d3;
}`

And REPLACE with:
`span {
  font-size: 250%;
  
}

span.userAction {
  font-size: 150%;
  font-weight: 300;
  text-align: center;
}

#cookieCleanup, #cookieCleanupIgnoreOpenTabs, #clearCookiesForDomain {
  background-color: #4CAF50;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width: 90%;
  margin-left: 15px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  border: solid 1px #20538D;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
  -webkit-transition-duration: 0.2s;
  -moz-transition-duration: 0.2s;
  transition-duration: 0.2s;
  -webkit-user-select:none;
  -moz-user-select:none;
  -ms-user-select:none;
  user-select:none;
}


#cookieCleanup:hover, #cookieCleanupIgnoreOpenTabs:hover, #clearCookiesForDomain:hover, #cookieCleanup:focus, #cookieCleanupIgnoreOpenTabs:focus, #clearCookiesForDomain:focus {
  background: #D3D3D3;
  border: solid 1px #2A4E77;
  color: black;
  text-decoration: none;
}
`

**Comment by ke-d** [comment]
Closing as this doesn't apply anymore.
