### ISSUE TITLE
Cookie from http://allestörungen.de won't be deleted with enabled Active Mode

### ISSUE THREAD

**Issue by spodermenpls** [Cookie-AutoDelete/Cookie-AutoDelete#142]
### Describe the Bug/Feature

The website http://allestörungen.de saves a cookie named ".xn--allestrungen-9ib.de", that continues to exist after closing the tab, while the Active Mode is being enabled and functions flawlessly everywhere else. Could this occur due to the umlaut in the domain name? 
I found www.förde-boston.de as another example for a domain with an umlaut, and it won't be deleted either.

### Steps for anyone to reproduce the bug

Visit http://allestörungen.de, close the tab, open the Cookie list and watch if it gets deleted after set time.

### Your settings 

- OS/version: Windows 10
- Browser/version: Firefox 55.0.3 - 64 bit
- Cookie AutoDelete version: 1.4.4

**Comment by ke-d** [comment]
Hmm, this is pretty odd. I'm testing with the latest build of 2.X.X. With 56, the cookie doesn't get deleted like you describe. However, in testing with 57, the cookie does get deleted with the exact same C-AD 2.X.X build. So I'm not sure whether if it's something with C-AD or with FF. I'll see what happens with Chrome.

Edit: 
Seems like the cookie gets deleted in Chrome so I think this is a browser issue in FF < 57.

**Comment by spodermenpls** [comment]
The causing punycode issue was fixed in FF 56, but needs to be activated by setting "network.standard-url.punycode-host" to enabled in about:config. CAD now deletes cookies from sites with umlauts without problems.

**Comment by mcnesium** [comment]
What does that setting do?

**Comment by spodermenpls** [comment]
@mcnesium It switches the internal URL encoding from Unicode to Punycode, so add-ons like uMatrix and CookieAD can properly handle URLs with umlauts and other special letters. It is activated by default in FF 57.

**Comment by ghost** [comment]
Upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=945240
