### ISSUE TITLE
Feature Request: Ability to Save/Delete Specific Cookies from a Domain

### ISSUE THREAD

**Issue by 20161220-rootfest** [Cookie-AutoDelete/Cookie-AutoDelete#143]
### Describe the Bug/Feature
It would be helpful if I could see the names of the cookies being stored and White/Grey/BlackList specific cookies. For example, say I want to save the cookies related to game saves from a particular site, but not whatever other cookies that site might want to store.

### Your settings 

- Cookie AutoDelete version: 1.4.0

**Comment by mrdokenny** [comment]
Duplicate of #68
