### ISSUE TITLE
Request: follow domain-change in open tab 

### ISSUE THREAD

**Issue by MR57** [Cookie-AutoDelete/Cookie-AutoDelete#250]
Hi,
Cookie-AutoDelete is a great tool, but I'm missing one setting (or I am overlooking it or doing something wrong, in which case I'd appreciate any hint):

To set Cookie-AutoDelete to a handle domain-change within an open tab as the same domain, meaning not to delete the cookies this tab currently has open.

For example, when a shop site redirects to paypal.com, please do not kill the merchant sites cookies.

Extra bonus would be if one could enter a list of domains for which this setting should work (as - for example - youtube does a short redirect to google.com one might not want to keep the google-cookies...)

Thanks & best wishes
Mark

**Comment by mrdokenny** [comment]
I don't think it's possible to manually make an exception for ALL merchant sites. I would just greylist the merchant sites you actually use or disable auto clean temporarily.

**Comment by MR57** [comment]
Then skip the whitelisting, how about adding the proposed setting "follow domain-change in open tab"? Other cookie-deleting addons have this and it is *very* helpful.
