### ISSUE TITLE
auto-whitelist browser internal pages

### ISSUE THREAD

**Issue by Nindaleth** [Cookie-AutoDelete/Cookie-AutoDelete#32]
For schemes and pages such as moz-extension://, chrome://, about:config, about:addons etc... it would provide a better user experience to change the taskbar icon background to whitelisted/blue and to remove the "add to whitelist" menu item - AFAIK no cookies are provided by these pages and no whitelist entry is created even if I click the menu item to do it.

In comparison, SDC addon stays armed/red, but modifies its menu items.

**Comment by mrdokenny** [comment]
That something that pretty trivial so low priority for this. Also when you click add to whitelist, it adds whatever is under the "Host Website" says at that page. 

>  moz-extension://, chrome://, about:config, about:addons 

So for those pages, "Host Website" is undefined, so the extension doesn't add anything.

**Comment by ke-d** [comment]
Closing as some extensions sometimes do create cookies and sometimes the user might want to whitelist some of them.
