### ISSUE TITLE
Incorrect terminology: URL ≠ Domain

### ISSUE THREAD

**Issue by alexander255** [Cookie-AutoDelete/Cookie-AutoDelete#61]
### Description of Problem

When visiting the *Cookie-Whitelist* section of the add-on preferences, all the whitelist entries are described as [URLs](https://en.wikipedia.org/wiki/URL), which they certainly are not (URLs must have at least a **scheme** and a hostname value separated by `://` or just `:`). The correct word you're looking for is *Domain name* or, shorter, *Domain*. :slightly_smiling_face: 

This is particularly confusing if you, at the same time, open the Firefox cookie settings "dialog-thing" which contains actual URLs/addresses (with HTTP or HTTPS scheme).

### Screenshot in which the bug can be seen

![bildschirmfoto am 2017-06-23 um 16 23 37-fullpage](https://user-images.githubusercontent.com/246386/27486278-5b3dd58e-5830-11e7-8a97-1b5f29d2e3a5.png)

### Steps for anyone to reproduce the bug

 1. Open the extension's settings
 2. Open the *Cookie-Whitelist* section

### Your settings 

- OS/version: Debian 9
- Browser/version: Firefox 54.0
- Cookie AutoDelete version: 1.3.1

**Comment by mrdokenny** [comment]
The German translation is out of date since 1.2.0 (still waiting on @Strayer but feel free to send in a PR [See #57] ). So some instances of that have been modified, but some still exists, so I'll probably edit the locales for the next cycle 1.5.0.

**Comment by Strayer** [comment]
The "Add URL" button still calls them URL, even in the updated translation. Decided to rather stay true to the original English translation file. (See PR #63)

I agree with the issue though, the wording is confusing.

**Comment by mrdokenny** [comment]
Well as long as there's an issue, I'll be reminded every time I come here. 😄

**Comment by mrdokenny** [comment]
Closing as there are no more references to URL at least in the en locale.
