### ISSUE TITLE
[Enhancement] Smaller popout menu UI

### ISSUE THREAD

**Issue by SW1FT** [Cookie-AutoDelete/Cookie-AutoDelete#67]
The popout menu seems way too big in my opinion, something smaller and with less whitespace would be greatly appreciated!

**Comment by mrdokenny** [comment]
What version are you on?

Do you mean the default size of the popup or when it shows "X deleted cookies cleared cookies from: ..." ?

Cause I think Firefox has a problem when there's a lot of sites shown. (kinda hard to see under the white background but the white space appears when you load the image on its own)

![screenshot 2017-06-25 18 33 02](https://user-images.githubusercontent.com/17077613/27521712-cf72ab0a-59d4-11e7-98cf-83dddcd6c3c0.png)

In Chrome, it seems to do better by just having a scroll bar (albeit a very long one)
![](http://i1-win.softpedia-static.com/screenshots/Cookie-AutoDelete_3.png)

**Comment by SW1FT** [comment]
I'm using Firefox so it might it. But I feel like the text and the size when hovering an option in general (even on Chrome) are too big, specially when compared to SDC. I think it would look a lot better if it was more condensed.

**Comment by mrdokenny** [comment]
I'll have to see what the popup looks like on Firefox Mobile once it becomes compatible before changing the popup UI up again, but in general, the popup looks bigger in Firefox for some reason.

**Comment by B00ze64** [comment]
I am copying this here from another bug which has to do with the Icon and not the UI. In my Chrome browser the UI is also pretty "spaced-out" and not wide enough, many lines "wrap" to a second line.
Here is how it looks in Chrome 60:
![autodeleteaddon](https://user-images.githubusercontent.com/15389810/30246266-2a3fa61c-95c3-11e7-8c0d-f752a372362b.png)

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
