### ISSUE TITLE
[BUG]  No language setting

### ISSUE THREAD

**Issue by Agych** [Cookie-AutoDelete/Cookie-AutoDelete#755]
**Describe the bug**

Cannot select language.

**Expected behavior**

Language setting in "Settings".

**Additional context**

Extension language is set automatically, according to the browser language.
No option to select language manually.

**Comment by kennethtran93** [comment]
That is currently intentional as I call browser.i18n.getMessage (WebExtension API) to get locale translations.

Otherwise it will take a while for me to build a function to transcribe it.
