### ISSUE TITLE
Don't change the icon color when the badge is visible

### ISSUE THREAD

**Issue by nkestrel** [Cookie-AutoDelete/Cookie-AutoDelete#76]
This is a solution proposal to some of the issues raised in #66. Changing the icon color gives useful feedback when there is no badge (#4) but it seems redundant to do this when the badge is visible. Since the badge matches the icon color, there is no contrast between the two and they merge into an ugly blob of color. Retaining the original icon color when the badge is enabled preserves the integrity of the logo and makes it more recognizable without sacrificing feedback.

![Icon color comparison](https://i.imgur.com/LW3cAAi.png)

**Comment by mrdokenny** [comment]
Generally I use upvotes/comments to gauge the interest of a feature. So I'll see what other people think since it's a visual tweak.

**Comment by mrdokenny** [comment]
@nkestrel You did that in code or is that just a mockup?

**Comment by B00ze64** [comment]
Why not use a fixed badge color and keep changing the icon color? Use black for the badge. On my system, in Chrome, the badge is tiny, we see more of the icon than the badge...

**Comment by nkestrel** [comment]
@mrdokenny I just renamed the icons. 😏

**Comment by drcheap** [comment]
As a point of reference, I have 3 other add-ons with counter badge overlays.  They all use the fixed-badge-color idea as @B00ze64 suggested.  One is black, one is grey, and one matches the icon (and thus has the same low-contrast issue).

![image](https://user-images.githubusercontent.com/10265909/33058077-6e044c4a-ce53-11e7-92a0-0985909f013d.png)

**Comment by kennethtran93** [comment]
If you would like to give it a try, head on over to PR #713 and download the latest build (in comments) and let me know if there's any tweaks that need to be looked into.
