### ISSUE TITLE
Whitelist items list takes way too much scrolling.

### ISSUE THREAD

**Issue by Betsy25** [Cookie-AutoDelete/Cookie-AutoDelete#79]
First, thanks for this brilliant replacement for "Self Destructing Cookies".

Items in Whitelist pane take way too much vertical space.
Is it possible to make the items narrower to each other, and not waste so much space in the whitelist pane, it might look pretty neat when you only have a few sites there, but over time, as the list grows, it becomes a real pain to work with and keep oversight.

- OS/version: Win 7 x64
- Browser/version: Firefox Nightly 56.0a1
- Cookie AutoDelete version: 1.4.0

**Comment by mrdokenny** [comment]
I'm curious, how many items do you have?

**Comment by Betsy25** [comment]
> I'm curious, how many items do you have?
A couple of dozens, but eventually, as with everything, it will continue growing over time.

**Comment by mrdokenny** [comment]
Is the oversight mean that you remove sites eventually? Cause I never really intend the grey/white list to be micromanaging.

**Comment by Betsy25** [comment]
Well, eventually when we leave a forum/site for what it is, we like to clean things up and not having our browser keep storing cookies which we no longer need, than it's handy to remove them from the Whitelist.

btw, regarding the other [issue I already closed](https://github.com/mrdokenny/Cookie-AutoDelete/issues/80), is that feature already properly implemented, since whenever the option is checked, the whole whitelist is blank again the next session in Firefox, no matter if we use contextual identities or not, after the next browser restart, the lists are completely empty, is that to be expected ?

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
