### ISSUE TITLE
Not available for your platform (OpenBSD)

### ISSUE THREAD

**Issue by janj-su** [Cookie-AutoDelete/Cookie-AutoDelete#86]
### Describe the Bug/Feature
While visiting https://addons.mozilla.org/en-GB/firefox/addon/cookie-autodelete/ there is a message "Not available for your platform" by selecting "Add to Firefox" -> "Install for Linux Anyway" I can still add the add-on and everything seems to work without any issues but I think that it may discourage people from this great add-on.

### Steps for anyone to reproduce the bug

Visit AMO from Firefox running on OpenBSD. :-/

### Your settings 

- OS/version: OpenBSD 6.1
- Browser/version: Firefox 54.0.1 (Mozilla/5.0 (X11; OpenBSD amd64; rv:54.0) Gecko/20100101 Firefox/54.0)
- Cookie AutoDelete version: 1.4.1

**Comment by mrdokenny** [comment]
I don't use that OS so I can't really test this, but it might be a problem with AMO, since linux is enabled on AMO on my side.

**Comment by janj-su** [comment]
According to some light testing on a Windows machine it seems to be dependent on the User Agent so you should be able to see it by following http://johnbokma.com/mexit/2004/04/24/changinguseragent.html and setting the agent string to: Mozilla/5.0 (X11; OpenBSD amd64; rv:54.0) Gecko/20100101 Firefox/54.0

I don't know how the available platforms are set but maybe it is possible for you to compare with https://github.com/EFForg/https-everywhere which does not show this "issue" for me.

**Comment by rugk** [comment]
Linux != (Open)BSD. Still, however, it is Firefox and AFAIK all add-ons should work on all OSes in Firefox if you have an up-to-date version of Firefox.

**Comment by Atavic** [comment]
OpenBSD 6.0 tightened security by losing Linux compatibility. Some required packages have been left out, while closing potential security loopholes.

**Comment by ke-d** [comment]
Closing as I started using "All platforms" when uploading.
