### ISSUE TITLE
Quick-Link to native cookie list

### ISSUE THREAD

**Issue by gharry-bsd** [Cookie-AutoDelete/Cookie-AutoDelete#87]
I'd love to have a shortcut to the native cookie listing/managing page.
Benefit:
- Users can quickly view currently present cookies.
- Users can easily alter native cookies-permissions with the additonal help of "CookieMan Context". 

The Exterminator has such a shortcut and I very much like it and use it permanently.

Thanks,

-garry

**Comment by mrdokenny** [comment]
Do you mean the one in `about:preferences#privacy` or in CAD settings?

**Comment by gharry-bsd** [comment]
Thank you for your quick response! Unfortunately I'm not familar with Moz//FF/XUL/Win terms; don't knwo what CAD means, but the former is clearly not what I mean.
Please see https://addons.cdn.mozilla.net/user-media/previews/full/20/20983.png.
This still exists in FF52, while clicking through the XUL-GUI leads to a modernized version of the same window.
The add-on supports both and that's the destination I want to be able to reach as quick as possible :-)

Thanks,

-garry

**Comment by mrdokenny** [comment]
CAD is the shortname for Cookie AutoDelete. 

Pretty sure I don't have access to that, but since there's a Cookie WebExtension API, someone could make a windowed cookie manager that's similar in the picture. Unfortunately, that is out of scope for this project.

Maybe you'll have better luck with this extension:

https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/

**Comment by synte** [comment]
I would find a direct link from the toolbar icon to `about:preferences#privacy` helpful. Please consider adding it. Thanks.

**Comment by kennethtran93** [comment]
This is now blocked as a webextension API limitations as a priviledged about: URL.  Until that is allowed the api call returns an Error of Illegal URL.
![Screenshot_20200506_100709](https://user-images.githubusercontent.com/6724477/81206722-5eaa6580-8f81-11ea-9305-b45465d19574.png)
