### ISSUE TITLE
Wildcard domains can't be entered

### ISSUE THREAD

**Issue by dzm06** [Cookie-AutoDelete/Cookie-AutoDelete#96]
### Describe the Bug/Feature
The domain wildcard feature doesn't allow entry of wildcards. Trying to enter something like *.google.com produces no visual feedback, but in the console is an error message that says 

```
TypeError: http://www.*.google.com is not a valid URL.  background-webpack.js:138:18
	getHostname moz-extension://db04df1d-ced7-8045-ba26-b81d629f2728/background-webpack.js:138:18
	getHostname moz-extension://db04df1d-ced7-8045-ba26-b81d629f2728/background-webpack.js:812:10
	addURLFromInput moz-extension://db04df1d-ced7-8045-ba26-b81d629f2728/settings/settings.js:191:25
	<anonymous> moz-extension://db04df1d-ced7-8045-ba26-b81d629f2728/settings/settings.js:441:3
```

- OS/version: macOS 10.13b5
- Browser/version: Firefox 55
- Cookie AutoDelete version: 1.4.1

**Comment by mrdokenny** [comment]
I'm using the [HTML5 URL input field](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Global_%3Cinput%3E_attributes) which does not support wildcards.

**Comment by drdaeman** [comment]
There is a related bug: I've just tried to add "*.google.com" and the list became visually empty. The only way to fix it seems to be is to resetting the settings (the settings tab becomes unresponsive for some reason, need to close it and open anew).

The extension seem to add an empty string for the domain name, and this breaks with "SyntaxError: An invalid or illegal string was specified" at settings.js:270, on `td.classList.add(arrayItem)`. There, the `arrayItem` is just an empty string (`""`).

Having `listType` as a classname makes sense, but I'm not sure why the domain names are used as classnames there - I suppose it's a mistake?

CAD 1.4.0 (up-to-date, from AMO) on Firefox DevEdition 56.0b3

**Comment by CodingMarkus** [comment]
I just ran into the same problem. I tried to enter a wildcard domain and my whitelist became empty. Apparently the settings are still there, though, as my cookie are not cleaned for whitelist domains. I wanted to whitelist all subdomains of a domain as adding just the domain there didn't protect subdomain cookies from being cleared. The reason why I even tried that was the help text on the settings page. It said

> When enabled, *.example.com will match example.com. Turning this off gives you more granular control over your lists.

So it sounded like "*.example.com" is a valid list entry

CAD 1.4 on Firefox 56.0b12

**Comment by bbenoit** [comment]
Same as @drdaeman and @CodingMarkus here.
I have tried to:
 - add a few domains to the _white list_ with the menu
 - export the _white list_
 - edit the export and add domains with wildcard
 - re-import the list

And it seems to be ok. Domains with wildcard are shown in the list.
**But** the tag with the number of cookies is still red when I browse to a subdomain of one of the domains with wildcard.
Needs further testing, I guess...

C.AD 1.4 on Firefox 57.0b1 (64-bit)

**Comment by ke-d** [comment]
@bbenoit Wildcards are not supported on that version. 2.X.X will add support for it.

**Comment by ke-d** [comment]
Closed for the release of 2.X.X
