### ISSUE TITLE
[SUPPORT]  Cookies not deleting

### ISSUE THREAD

**Issue by Mr-Personality** [Cookie-AutoDelete/Cookie-AutoDelete#976]
I've just done the following:

1. Installed Cookie AutoDelete for the first time
2. Visited my regular sites like email, and whitelisted them
3. Clicked the big yellow "Clean" button, expecting all non-whitelisted cookies to be deleted

But if I go to Options > Privacy & Security > Cookies and Site Data > Manage Data, there are many cookies still there that have not been whitelisted.

Am I doing something wrong?

**Comment by kennethtran93** [comment]
Are the entries remaining part of your list of opened tabs?  If not, what sites are remaining, and is it the cookie count that is not zero or that there may be some data remaining.  They do not necessarily correlate to one another.
